// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDVeUsb3Z3Ge7XKlCWmPIf2t1kKVZgyT4',
    appId: '1:791093127:android:f0b769d52aafedf2d8bd22',
    messagingSenderId: '791093127',
    projectId: 'kafe-app-8a7ee',
    storageBucket: 'kafe-app-8a7ee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBo8awe2kmoG2p39jUTxF0eBSrKadXIyuM',
    appId: '1:791093127:ios:764e59833df946a5d8bd22',
    messagingSenderId: '791093127',
    projectId: 'kafe-app-8a7ee',
    storageBucket: 'kafe-app-8a7ee.appspot.com',
    androidClientId: '791093127-5aun2k9nab6baffrg6th22gt533fltj0.apps.googleusercontent.com',
    iosClientId: '791093127-52q6h9jqldoga8ndsokfilos0hjve9ia.apps.googleusercontent.com',
    iosBundleId: 'com.example.kafeApp',
  );
}
